Default BookReader to 1up instead of 2up on mobile
internetarchive/bookreader pull request #1104
Opened 2022-11-11 12:18 UTC by nsharma123

https://webarchive.jira.com/browse/WEBDEV-5253

2022-11-11 21:38 UTC, iisa approved these changes
@nsharma123 code looks good but we cannot merge the build files into main as they get generated by release flow. can u remove those before merge? thanks!

2022-11-11 21:38 UTC, iisa commented on src/BookReader.js
> +    nextMode = this.options.defaults === 'mode/1up' ? this.constMode1up : this.constMode2up;
:nice:

2022-11-11 21:38 UTC, iisa commented
@nsharma123 please remove build files before merge. thanks!

2022-11-11 21:38 UTC, iisa commented
tests also need to be checked, they are failing

2022-11-14 06:38 UTC, nsharma123 commented
yes, I will remove those and fix the tests as well. Thanks!

2022-12-14 16:17 UTC, iisa requested changes
@nsharma123 thanks for the fix! got a couple of suggestions, I just want us to ensure we cover thumbnail mode when it is set to default. thank you!

2022-12-14 16:17 UTC, iisa commented on src/BookReader.js
> +  if (null != this.options.defaults) {
this conditional is "[yoda style](https://eslint.org/docs/latest/rules/yoda)". we don't usually use this style in BR.

can a falsey work? `if (!this.options.defaults)` ?

2022-12-14 16:17 UTC, iisa commented on src/BookReader.js
> +    nextMode = this.options.defaults === 'mode/1up' ? this.constMode1up : this.constMode2up;
Suggestion, potential blocker: we have possible 3rd option for thumbnail view - can you add support here for it? @nsharma123

2022-12-15 07:34 UTC, iisa approved these changes
thanks for making sure all modes are covered

2022-12-15 07:35 UTC, iisa commented
looks good once tests pass

2022-12-15 09:41 UTC, merged