Downloads Panel - does not show if there are no downloadableTypes available
internetarchive/bookreader pull request #1172
Opened 2023-03-28 07:17 UTC by iisa

+ unit test
+ demo

### Testing
- go to review app - 
- open side panel to confirm download pane is there
- close side panel
- click - Remove Download panel
- open side panel
- ✅ no download panel anymore

2023-03-28 18:03 UTC, dualcnhq approved these changes
:lgtm:

2023-03-28 19:14 UTC, cdrini requested changes
Lgtm! I think we should remove the option to hide the download options from the demo; I'm not sure what value it will provide for the demo going forward outside the context of this PR. Our demos are getting a little large and difficult to maintain cause they're written in older JS. Keeping it slim is preferable :)

2023-03-29 16:50 UTC, iisa commented on BookReaderDemo/IADemoBr.js
> +
ok sound good. i can remove.

2023-03-29 16:57 UTC, cdrini approved these changes
Lgtm!

2023-03-29 17:46 UTC, merged