Refactor volumes sorting state
internetarchive/bookreader pull request #893
Opened 2021-11-30 02:54 UTC by dualcnhq

2021-12-02 02:36 UTC, cdrini requested changes
So close! 🎉

2021-12-02 02:36 UTC, cdrini commented on src/plugins/plugin.url.js
> +        }
Put these changes in your other PR, and then rebase this ; that way this PR becomes just about the volume sorting stuff!

2021-12-15 00:27 UTC, cdrini approved these changes
Ok, lgtm! In a future PR, we should start deleting all the old refs to the old URL plugin 🎉 


Tested in FF95:

- Flipping pages updates URL
- Changing url and reloading opens to right page

- Changing volume order updates url
- Loading page with volume order param shows correct order

- Clicking volume reloads page with that volume
- Trailing slash works https://www-clau.archive.org/details/SubBookTest/

- Doing search shows up in url
- url with search auto-triggers search

2021-12-17 06:42 UTC, iisa approved these changes

2021-12-20 22:37 UTC, merged